### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by Dud3z** [maovidal/home-assistant_addons#27]
Hi,

if i try to start the container it tells me "s6-overlay-suexec: fatal: can only run as pid 1" in the logs.

i'd really like to try you Addon because i hope to get information from my gigaset gateway.

**Comment by maovidal** [comment]
Hey @Dud3z 
Thank you for the interest on this.
I have a long overdue upgrade for this. Could you give me until next weekend?

**Comment by Dud3z** [comment]
Hi @maovidal,

absolutely! Thank you!

**Comment by maovidal** [comment]
Hey @Dud3z 
I have published the 0.1.1 version that should fix that error.
Could you upgrade and test please?
